// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"

/* Forward Declarations */
// Parameterized interface forward declarations (C)

// Collection interface definitions

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
enum __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel
    {
        __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_Text = 0,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_Image = 1,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_Table = 2,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_Container = 3,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_Menu = 4,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_ToolBar = 5,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_AddressBar = 6,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_Toolpane = 7,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_TabBar = 8,
    __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionLabel_TitleBar = 9,
};
#endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
struct __x_ABI_CMicrosoft_CWindows_CVision_CScreenRegionBoundingBox
    {
        UINT32 Left;
    UINT32 Top;
    UINT32 Right;
    UINT32 Bottom;
};
#endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

