// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.Windows.PrivateCommon.h"
#include "Windows.Graphics.h"
// Importing Collections header
#include "Windows.Foundation.Collections.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2 __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2 __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3 __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2 __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3 __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView;

#if !defined(____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView;

    typedef struct __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Current)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView* result);
    HRESULT (STDMETHODCALLTYPE* get_HasCurrent)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* MoveNext)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        UINT32 itemsLength,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView* items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl;

    interface __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView
    {
        CONST_VTBL struct __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView;

    typedef struct __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* First)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView** result);

        END_INTERFACE
    } __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl;

    interface __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView
    {
        CONST_VTBL struct __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__
    
typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData;

#if !defined(____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData;

    typedef struct __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Current)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData* result);
    HRESULT (STDMETHODCALLTYPE* get_HasCurrent)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* MoveNext)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        UINT32 itemsLength,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData* items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl;

    interface __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData
    {
        CONST_VTBL struct __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData;

    typedef struct __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* First)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData** result);

        END_INTERFACE
    } __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl;

    interface __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData
    {
        CONST_VTBL struct __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView;

    typedef struct __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetAt)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        UINT32 index,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView* result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* IndexOf)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView value,
        UINT32* index,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* This,
        UINT32 startIndex,
        UINT32 itemsLength,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView* items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl;

    interface __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView
    {
        CONST_VTBL struct __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData;

    typedef struct __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetAt)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        UINT32 index,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData* result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* IndexOf)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData value,
        UINT32* index,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* This,
        UINT32 startIndex,
        UINT32 itemsLength,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData* items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl;

    interface __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData
    {
        CONST_VTBL struct __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewDataVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncAction __x_ABI_CWindows_CFoundation_CIAsyncAction;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

typedef struct __x_ABI_CWindows_CGraphics_CPointInt32 __x_ABI_CWindows_CGraphics_CPointInt32;

typedef struct __x_ABI_CWindows_CGraphics_CRectInt32 __x_ABI_CWindows_CGraphics_CRectInt32;

typedef enum __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxAxisDirectionInternal __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxAxisDirectionInternal;

typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CModelProperties __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CModelProperties;

typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxImageOptions __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxImageOptions;

enum __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxAxisDirectionInternal
    {
        __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxAxisDirectionInternal_xAndYAxis = 0,
    __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxAxisDirectionInternal_xAxisOnly = 1,
    __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxAxisDirectionInternal_yAxisOnly = 2,
};

struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CModelProperties
    {
        INT32 EncodingSize;
    INT32 MaxPointCount;
};

struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxImageOptions
    {
        UINT32 NumberOfFrames;
    FLOAT RotationalRadius;
    UINT32 NumberOfLayers;
    FLOAT OffsetFactor;
    enum __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxAxisDirectionInternal ParallaxAxis;
};

#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateAsync)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView inputBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData inputBufferViewData,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView outputBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData outputBufferViewData,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSessionVtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* Create)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2* This,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* inputImageBufferResource,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* outputImageBufferResource,
        UINT32 priority,
        UINT32 frequency);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2Vtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIDepthMapCreatorSession2_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* InitializeWithImageBuffer)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* inputImageBufferResource,
        UINT32 priority,
        UINT32 frequency,
        UINT32 encodingLength,
        FLOAT* encoding);
    HRESULT (STDMETHODCALLTYPE* GetBackground)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This,
        UINT32 encodingLength,
        FLOAT* encoding,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* outputImageBufferResource,
        UINT32 rectsLength,
        struct __x_ABI_CWindows_CGraphics_CRectInt32* rects,
        UINT32 inclusionPointsLength,
        struct __x_ABI_CWindows_CGraphics_CPointInt32* inclusionPoints,
        UINT32 exclusionPointsLength,
        struct __x_ABI_CWindows_CGraphics_CPointInt32* exclusionPoints,
        UINT32 priority,
        UINT32 frequency);
    HRESULT (STDMETHODCALLTYPE* GetModelProperties)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession* This,
        struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CModelProperties* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSessionVtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageObjectExtractorSession_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* ScaleImage)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession* This,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* inputImageBufferResource,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* outputImageBufferResource,
        INT32 width,
        INT32 height,
        UINT32 priority,
        UINT32 frequency);
    HRESULT (STDMETHODCALLTYPE* MaxSupportedScaleFactor)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession* This,
        INT32* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSessionVtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageScalerSession_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* RemoveBackground)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession* This,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* inputImageBufferResource,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* outputImageBufferResource);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSessionVtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIImageSegmenterSession_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateParallaxImagesAsync)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView inputView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData inputViewData,
        __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* outputViews,
        __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* outputViewData,
        struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxImageOptions options,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSessionVtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateParallaxImagesAsync)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView inputView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData inputViewData,
        __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferView* outputViews,
        __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CPrivateCommon__CImageBufferViewData* outputViewData,
        struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxImageOptions options,
        UINT32 priority,
        UINT32 frequency,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2Vtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession2_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateParallaxImages)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3* This,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* inputImageBufferResource,
        UINT32 outputImageBufferResourcesLength,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource** outputImageBufferResources,
        struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CParallaxImageOptions options,
        UINT32 priority,
        UINT32 frequency);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3Vtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CIParallaxCreatorSession3_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* RemoveBackgroundAsync)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView inputImageBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData inputImageBufferViewData,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView outputImageBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData outputImageBufferViewData,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView fgMaskImageBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData fgMaskImageBufferViewData,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView bgMaskImageBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData bgMaskImageBufferViewData,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSessionVtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* RemoveBackgroundAsync)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView inputImageBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData inputImageBufferViewData,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView outputImageBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData outputImageBufferViewData,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView fgMaskImageBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData fgMaskImageBufferViewData,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView bgMaskImageBufferView,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData bgMaskImageBufferViewData,
        UINT32 priority,
        UINT32 frequency,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2Vtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession2_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* RemoveBackground)(__x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3* This,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* inputImageBufferResource,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* outputImageBufferResource,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* fgMaskImageBufferResource,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* bgMaskImageBufferResource,
        UINT32 priority,
        UINT32 frequency);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3Vtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImagingInternal_CITrimapImageSegmenterSession3_INTERFACE_DEFINED__) */
    
