// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.Windows.PrivateCommon.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CImageContentAnalysisScores __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CImageContentAnalysisScores;

typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CTextContentAnalysisScores __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CTextContentAnalysisScores;

struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CImageContentAnalysisScores
    {
        UINT32 numCategoryLevels;
    FLOAT normalContentLevel;
    FLOAT adultHarmContentLevel;
    FLOAT racyContentLevel;
    FLOAT goryContentLevel;
    FLOAT violenceContentLevel;
};

struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CTextContentAnalysisScores
    {
        UINT32 numCategoryLevels;
    UINT32 selfHarmContentLevel;
    UINT32 violentContentLevel;
    UINT32 hateContentLevel;
    UINT32 sexualContentLevel;
};

#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* ValidateImage)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession* This,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* inputImageBufferResource,
        UINT32 priority,
        UINT32 frequency,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* AnalyzeImage)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession* This,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* inputImageBufferResource,
        UINT32 priority,
        UINT32 frequency,
        struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CImageContentAnalysisScores* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSessionVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CIImageContentModerationSession_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* IsTextBlocked)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession* This,
        HSTRING query,
        HSTRING inputLanguage,
        boolean* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSessionVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextBlockListSession_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSessionVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* AnalyzeText)(__x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession* This,
        HSTRING text,
        UINT32 priority,
        UINT32 frequency,
        struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CTextContentAnalysisScores* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSessionVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSessionVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CContentModerationInternal_CITextContentModerationSession_INTERFACE_DEFINED__) */
    
