// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.UI.h"
#include "Windows.Data.Json.h"
#include "Windows.Web.Http.h"
#include "Windows.Web.Http.Headers.h"
// Importing Collections header
#include "Windows.Foundation.Collections.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse;

#endif // ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult;

#if !defined(____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult;

    typedef struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResultVtbl;

    interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResultVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult;

    typedef struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResultVtbl;

    interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResultVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult_INTERFACE_DEFINED__
    
typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult;

#if !defined(____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult;

    typedef struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResultVtbl;

    interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResultVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult;

    typedef struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResultVtbl;

    interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResultVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING __x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING;

    typedef struct __x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Key)(__x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
        HSTRING* result);
    HRESULT (STDMETHODCALLTYPE* get_Value)(__x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
        HSTRING* result);

        END_INTERFACE
    } __x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl;

    interface __x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING;

    typedef struct __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Current)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
        __x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING** result);
    HRESULT (STDMETHODCALLTYPE* get_HasCurrent)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* MoveNext)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
        UINT32 itemsLength,
        __x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING** items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl;

    interface __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING;

    typedef struct __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* First)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING* This,
        __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING** result);

        END_INTERFACE
    } __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl;

    interface __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING_HSTRING_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CWindows_CData_CJson_CIJsonValue_FWD_DEFINED__
#define ____x_ABI_CWindows_CData_CJson_CIJsonValue_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CData_CJson_CIJsonValue __x_ABI_CWindows_CData_CJson_CIJsonValue;

#endif // ____x_ABI_CWindows_CData_CJson_CIJsonValue_FWD_DEFINED__

#if !defined(____x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue __x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

    typedef struct __x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Key)(__x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        HSTRING* result);
    HRESULT (STDMETHODCALLTYPE* get_Value)(__x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        __x_ABI_CWindows_CData_CJson_CIJsonValue** result);

        END_INTERFACE
    } __x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl;

    interface __x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue
    {
        CONST_VTBL struct __x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

    typedef struct __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Current)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        __x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue** result);
    HRESULT (STDMETHODCALLTYPE* get_HasCurrent)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* MoveNext)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        UINT32 itemsLength,
        __x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue** items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl;

    interface __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue
    {
        CONST_VTBL struct __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

    typedef struct __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* First)(__x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        __x_ABI_C__FIIterator_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue** result);

        END_INTERFACE
    } __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl;

    interface __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue
    {
        CONST_VTBL struct __x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterable_1___x_ABI_C__FIKeyValuePair_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__
    
typedef interface __x_ABI_C__FIMapView_2_HSTRING_HSTRING __x_ABI_C__FIMapView_2_HSTRING_HSTRING;

#if !defined(____x_ABI_C__FIMapView_2_HSTRING_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIMapView_2_HSTRING_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIMapView_2_HSTRING_HSTRING __x_ABI_C__FIMapView_2_HSTRING_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIMapView_2_HSTRING_HSTRING;

    typedef struct __x_ABI_C__FIMapView_2_HSTRING_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* Lookup)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This,
        HSTRING key,
        HSTRING* result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* HasKey)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This,
        HSTRING key,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* Split)(__x_ABI_C__FIMapView_2_HSTRING_HSTRING* This,
        __x_ABI_C__FIMapView_2_HSTRING_HSTRING** first,
        __x_ABI_C__FIMapView_2_HSTRING_HSTRING** second);

        END_INTERFACE
    } __x_ABI_C__FIMapView_2_HSTRING_HSTRINGVtbl;

    interface __x_ABI_C__FIMapView_2_HSTRING_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIMapView_2_HSTRING_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIMapView_2_HSTRING_HSTRING_INTERFACE_DEFINED__
    
typedef interface __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

#if !defined(____x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue;

    typedef struct __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* Lookup)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        HSTRING key,
        __x_ABI_CWindows_CData_CJson_CIJsonValue** result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* HasKey)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        HSTRING key,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* Split)(__x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue* This,
        __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue** first,
        __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue** second);

        END_INTERFACE
    } __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl;

    interface __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue
    {
        CONST_VTBL struct __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValueVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIMap_2_HSTRING_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIMap_2_HSTRING_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIMap_2_HSTRING_HSTRING __x_ABI_C__FIMap_2_HSTRING_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIMap_2_HSTRING_HSTRING;

    typedef struct __x_ABI_C__FIMap_2_HSTRING_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* Lookup)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
        HSTRING key,
        HSTRING* result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* HasKey)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
        HSTRING key,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetView)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
        __x_ABI_C__FIMapView_2_HSTRING_HSTRING** result);
    HRESULT (STDMETHODCALLTYPE* Insert)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
        HSTRING key,
        HSTRING value,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* Remove)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This,
        HSTRING key);
    HRESULT (STDMETHODCALLTYPE* Clear)(__x_ABI_C__FIMap_2_HSTRING_HSTRING* This);

        END_INTERFACE
    } __x_ABI_C__FIMap_2_HSTRING_HSTRINGVtbl;

    interface __x_ABI_C__FIMap_2_HSTRING_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIMap_2_HSTRING_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIMap_2_HSTRING_HSTRING_INTERFACE_DEFINED__
    
typedef struct __x_ABI_CMicrosoft_CUI_CWindowId __x_ABI_CMicrosoft_CUI_CWindowId;

typedef enum __x_ABI_CWindows_CFoundation_CAsyncStatus __x_ABI_CWindows_CFoundation_CAsyncStatus;

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncInfo __x_ABI_CWindows_CFoundation_CIAsyncInfo;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIUriRuntimeClass __x_ABI_CWindows_CFoundation_CIUriRuntimeClass;

#endif // ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue_FWD_DEFINED__
#define ____x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue __x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue;

#endif // ____x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CWeb_CHttp_CIHttpResponseMessage_FWD_DEFINED__
#define ____x_ABI_CWindows_CWeb_CHttp_CIHttpResponseMessage_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CWeb_CHttp_CIHttpResponseMessage __x_ABI_CWindows_CWeb_CHttp_CIHttpResponseMessage;

#endif // ____x_ABI_CWindows_CWeb_CHttp_CIHttpResponseMessage_FWD_DEFINED__

typedef enum __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CCodeChallengeMethodKind __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CCodeChallengeMethodKind;

typedef enum __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CTokenFailureKind __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CTokenFailureKind;

enum __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CCodeChallengeMethodKind
    {
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CCodeChallengeMethodKind_None = 0,
    __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CCodeChallengeMethodKind_S256 = 1,
    __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CCodeChallengeMethodKind_Plain = 2,
};

enum __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CTokenFailureKind
    {
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CTokenFailureKind_ErrorResponse = 0,
    __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CTokenFailureKind_HttpFailure = 1,
    __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CTokenFailureKind_InvalidResponse = 2,
};

#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailureVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Error)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ErrorDescription)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ErrorUri)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* get_State)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_AdditionalParams)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure* This,
        __x_ABI_C__FIMapView_2_HSTRING_HSTRING** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailureVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailureVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_ResponseType)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_ResponseType)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_ClientId)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_ClientId)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_RedirectUri)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* put_RedirectUri)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* value);
    HRESULT (STDMETHODCALLTYPE* get_State)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_State)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_Scope)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Scope)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_CodeChallenge)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_CodeChallenge)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_CodeChallengeMethod)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        enum __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CCodeChallengeMethodKind* value);
    HRESULT (STDMETHODCALLTYPE* put_CodeChallengeMethod)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        enum __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CCodeChallengeMethodKind value);
    HRESULT (STDMETHODCALLTYPE* get_AdditionalParams)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* This,
        __x_ABI_C__FIMap_2_HSTRING_HSTRING** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory* This,
        HSTRING responseType,
        HSTRING clientId,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams** value);
    HRESULT (STDMETHODCALLTYPE* CreateInstance2)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory* This,
        HSTRING responseType,
        HSTRING clientId,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* redirectUri,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactoryVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateForAuthorizationCodeRequest)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics* This,
        HSTRING clientId,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams** result);
    HRESULT (STDMETHODCALLTYPE* CreateForAuthorizationCodeRequest2)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics* This,
        HSTRING clientId,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* redirectUri,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStaticsVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParamsStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_ResponseUri)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* get_Response)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse** value);
    HRESULT (STDMETHODCALLTYPE* get_Failure)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult* This,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthFailure** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResultVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResultVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestResult_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponseVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_State)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_Code)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_AccessToken)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_TokenType)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ExpiresIn)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_Scope)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_AdditionalParams)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* This,
        __x_ABI_C__FIMapView_2_HSTRING_HSTRING** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponseVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponseVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Authorization)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
        __x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue** value);
    HRESULT (STDMETHODCALLTYPE* put_Authorization)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
        __x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue* value);
    HRESULT (STDMETHODCALLTYPE* get_ProxyAuthorization)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
        __x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue** value);
    HRESULT (STDMETHODCALLTYPE* put_ProxyAuthorization)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
        __x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue* value);
    HRESULT (STDMETHODCALLTYPE* get_AdditionalHeaders)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* This,
        __x_ABI_C__FIMap_2_HSTRING_HSTRING** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory* This,
        __x_ABI_CWindows_CWeb_CHttp_CHeaders_CIHttpCredentialsHeaderValue* authorization,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactoryVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateForBasicAuthorization)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics* This,
        HSTRING clientId,
        HSTRING clientSecret,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStaticsVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthenticationStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* RequestAuthWithParamsAsync)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This,
        struct __x_ABI_CMicrosoft_CUI_CWindowId parentWindowId,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* authEndpoint,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthRequestParams* params,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CAuthRequestResult** operation);
    HRESULT (STDMETHODCALLTYPE* CompleteAuthRequest)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* responseUri,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* RequestTokenAsync)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* tokenEndpoint,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* params,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult** operation);
    HRESULT (STDMETHODCALLTYPE* RequestTokenAsync2)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* tokenEndpoint,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* params,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIClientAuthentication* clientAuth,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CSecurity__CAuthentication__COAuth__CTokenRequestResult** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStaticsVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIOAuth2ManagerStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailureVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Kind)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
        enum __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CTokenFailureKind* value);
    HRESULT (STDMETHODCALLTYPE* get_ErrorCode)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
        HRESULT* value);
    HRESULT (STDMETHODCALLTYPE* get_Error)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ErrorDescription)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ErrorUri)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* get_AdditionalParams)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure* This,
        __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailureVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailureVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_GrantType)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_GrantType)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_Code)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Code)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_RedirectUri)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* put_RedirectUri)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* value);
    HRESULT (STDMETHODCALLTYPE* get_CodeVerifier)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_CodeVerifier)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_ClientId)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_ClientId)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_Username)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Username)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_Password)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Password)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_Scope)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Scope)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_RefreshToken)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_RefreshToken)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_AdditionalParams)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams* This,
        __x_ABI_C__FIMap_2_HSTRING_HSTRING** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory* This,
        HSTRING grantType,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactoryVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateForAuthorizationCodeRequest)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CIAuthResponse* authResponse,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams** result);
    HRESULT (STDMETHODCALLTYPE* CreateForClientCredentials)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams** result);
    HRESULT (STDMETHODCALLTYPE* CreateForExtension)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* extensionUri,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams** result);
    HRESULT (STDMETHODCALLTYPE* CreateForRefreshToken)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics* This,
        HSTRING refreshToken,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParams** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStaticsVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestParamsStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_ResponseMessage)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This,
        __x_ABI_CWindows_CWeb_CHttp_CIHttpResponseMessage** value);
    HRESULT (STDMETHODCALLTYPE* get_Response)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse** value);
    HRESULT (STDMETHODCALLTYPE* get_Failure)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult* This,
        __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenFailure** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResultVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResultVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenRequestResult_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponseVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_AccessToken)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_TokenType)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ExpiresIn)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
        DOUBLE* value);
    HRESULT (STDMETHODCALLTYPE* get_RefreshToken)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_Scope)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_AdditionalParams)(__x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse* This,
        __x_ABI_C__FIMapView_2_HSTRING___x_ABI_CWindows__CData__CJson__CIJsonValue** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponseVtbl;

    interface __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponseVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse;
#endif /* !defined(____x_ABI_CMicrosoft_CSecurity_CAuthentication_COAuth_CITokenResponse_INTERFACE_DEFINED__) */
    
