// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.Windows.Widgets.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement;

#endif // ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory;

#endif // ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs;

#endif // ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

typedef struct __x_ABI_CWindows_CFoundation_CDateTime __x_ABI_CWindows_CFoundation_CDateTime;

typedef struct __x_ABI_CWindows_CFoundation_CTimeSpan __x_ABI_CWindows_CFoundation_CTimeSpan;

#ifndef ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIUriRuntimeClass __x_ABI_CWindows_CFoundation_CIUriRuntimeClass;

#endif // ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__

typedef enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementActionKind __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementActionKind;

typedef enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor;

enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementActionKind
    {
        __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementActionKind_Shown = 0,
    __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementActionKind_Engaged = 1,
};

enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor
    {
        __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor_Default = 0,
    __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor_Dark = 1,
    __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor_Light = 2,
    __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor_Accent = 3,
    __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor_Good = 4,
    __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor_Warning = 5,
    __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor_Attention = 6,
};

#if !defined(____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Id)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Id)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_PrimaryText)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_PrimaryText)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_SecondaryText)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_SecondaryText)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_LightModeIconUri)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* put_LightModeIconUri)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* value);
    HRESULT (STDMETHODCALLTYPE* get_DarkModeIconUri)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* put_DarkModeIconUri)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* value);
    HRESULT (STDMETHODCALLTYPE* get_PrimaryTextColor)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor* value);
    HRESULT (STDMETHODCALLTYPE* put_PrimaryTextColor)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor value);
    HRESULT (STDMETHODCALLTYPE* get_SecondaryTextColor)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor* value);
    HRESULT (STDMETHODCALLTYPE* put_SecondaryTextColor)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementTextColor value);
    HRESULT (STDMETHODCALLTYPE* get_CustomAccessibilityText)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_CustomAccessibilityText)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_IsSecondaryTextSubtle)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* put_IsSecondaryTextSubtle)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        boolean value);
    HRESULT (STDMETHODCALLTYPE* get_ShowBadgeIfUserNotEngaged)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* put_ShowBadgeIfUserNotEngaged)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        boolean value);
    HRESULT (STDMETHODCALLTYPE* get_ExpirationTime)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        struct __x_ABI_CWindows_CFoundation_CDateTime* value);
    HRESULT (STDMETHODCALLTYPE* put_ExpirationTime)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        struct __x_ABI_CWindows_CFoundation_CDateTime value);
    HRESULT (STDMETHODCALLTYPE* get_Duration)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        struct __x_ABI_CWindows_CFoundation_CTimeSpan* value);
    HRESULT (STDMETHODCALLTYPE* put_Duration)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement* This,
        struct __x_ABI_CWindows_CFoundation_CTimeSpan value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory* This,
        HSTRING id,
        HSTRING primaryText,
        HSTRING secondaryText,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* lightModeIcon,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* darkModeIcon,
        __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncement** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactoryVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_FeedProviderDefinitionId)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_FeedDefinitionId)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_AnnouncementId)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ActionKind)(__x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs* This,
        enum __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CAnnouncementActionKind* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgsVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CWidgets_CNotifications_CIFeedAnnouncementInvokedArgs_INTERFACE_DEFINED__) */
    
