// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2 __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3 __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost;

#endif // ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncAction __x_ABI_CWindows_CFoundation_CIAsyncAction;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__

typedef enum __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat;

typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferData __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferData;

typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView;

typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData;

enum __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat
    {
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat_Undefined = 0,
    __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat_Rgb24 = 1,
    __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat_Argb32 = 2,
    __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat_Rgba32 = 3,
    __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat_Bgra32 = 4,
    __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat_Gray8 = 5,
};

struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferData
    {
        UINT32 height;
    UINT32 width;
    enum __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat pixelFormat;
    UINT32 rowStride;
    UINT64 targetProcessHandle;
    UINT64 sourceProcessHandle;
};

struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView
    {
        UINT32 height;
    UINT32 width;
    enum __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat pixelFormat;
    UINT32 rowStride;
};

struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData
    {
        UINT64 targetProcessHandle;
    UINT64 sourceProcessHandle;
};

#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstanceVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* AnchorInstance)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance* This,
        IInspectable* instance);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstanceVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstanceVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIAnchorInstance_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessIdVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetSessionHostProcessId)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId* This,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessIdVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessIdVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIGetSessionHostProcessId_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivateVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetImageBufferView)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferView* result);
    HRESULT (STDMETHODCALLTYPE* GetImageBufferViewData)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This,
        UINT32 targetProcessId,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferViewData* result);
    HRESULT (STDMETHODCALLTYPE* SyncBufferWithOutValue)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This);
    HRESULT (STDMETHODCALLTYPE* GetImageBufferResource)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate* This,
        IInspectable* sessionAsInspectable,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivateVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivateVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferPrivate_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_BufferData)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferData* value);
    HRESULT (STDMETHODCALLTYPE* put_BufferData)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferData value);
    HRESULT (STDMETHODCALLTYPE* Buffer)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        UINT64* result);
    HRESULT (STDMETHODCALLTYPE* Width)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* Height)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* RowStride)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* BytesPerPixel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* Capacity)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* PixelFormat)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource* This,
        enum __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory* This,
        struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CImageBufferData bufferData,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource** value);
    HRESULT (STDMETHODCALLTYPE* CreateInstance2)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory* This,
        UINT32 height,
        UINT32 width,
        enum __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CPixelFormat pixelFormat,
        UINT32 rowStride,
        UINT64 targetProcessHandle,
        UINT64 sourceProcessHandle,
        __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResource** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactoryVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIImageBufferResourceFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManagerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* EnsureModelInitialized)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager* This);
    HRESULT (STDMETHODCALLTYPE* GenerateCacheModel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager* This,
        HSTRING offlineDriverPath);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManagerVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManagerVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* SetPackageFamilyName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2* This,
        HSTRING packageFamilyName);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2Vtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager2_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GenerateCacheModel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This);
    HRESULT (STDMETHODCALLTYPE* SetCorrelationVector)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This,
        HSTRING correlationVector);
    HRESULT (STDMETHODCALLTYPE* IsModelCacheReady)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3* This,
        boolean* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3Vtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CIModelManager3_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHostVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* NotifyExpiredSessionHost)(__x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost* This,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHostVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHostVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CPrivateCommon_CINotifyExpiredSessionHost_INTERFACE_DEFINED__) */
    
