// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.Graphics.Imaging.h"
#include "Microsoft.Windows.AI.h"
#include "Microsoft.Windows.Workloads.h"
#include "Windows.Graphics.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine;

#endif // ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText;

#endif // ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord;

#endif // ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer;

#endif // ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions;

#endif // ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics;

#endif // ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText;

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText;

    typedef struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedTextVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
        __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedTextVtbl;

    interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedTextVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText_INTERFACE_DEFINED__
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText;

    typedef struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedTextVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedTextVtbl;

    interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedTextVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText_INTERFACE_DEFINED__
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer;

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer;

    typedef struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
        __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizerVtbl;

    interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizerVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer_INTERFACE_DEFINED__
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer;

    typedef struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizerVtbl;

    interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizerVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer_INTERFACE_DEFINED__
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__

typedef interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

typedef interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

#if !defined(____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    typedef struct __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl;

    interface __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    typedef struct __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Progress)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* handler);
    HRESULT (STDMETHODCALLTYPE* get_Progress)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double** result);
    HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl;

    interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    typedef struct __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* asyncInfo,
        DOUBLE progressInfo);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl;

    interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_FWD_DEFINED__

typedef enum __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState;

typedef enum __x_ABI_CMicrosoft_CWindows_CWorkloads_CWorkloadPriority __x_ABI_CMicrosoft_CWindows_CWorkloads_CWorkloadPriority;

typedef enum __x_ABI_CWindows_CFoundation_CAsyncStatus __x_ABI_CWindows_CFoundation_CAsyncStatus;

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncInfo __x_ABI_CWindows_CFoundation_CIAsyncInfo;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

typedef struct __x_ABI_CWindows_CFoundation_CPoint __x_ABI_CWindows_CFoundation_CPoint;

typedef struct __x_ABI_CWindows_CGraphics_CSizeInt32 __x_ABI_CWindows_CGraphics_CSizeInt32;

typedef enum __x_ABI_CMicrosoft_CWindows_CVision_CDetectedLineStyle __x_ABI_CMicrosoft_CWindows_CVision_CDetectedLineStyle;

typedef enum __x_ABI_CMicrosoft_CWindows_CVision_COrientationDetectionOptions __x_ABI_CMicrosoft_CWindows_CVision_COrientationDetectionOptions;

typedef struct __x_ABI_CMicrosoft_CWindows_CVision_CBoundingBox __x_ABI_CMicrosoft_CWindows_CVision_CBoundingBox;

typedef struct __x_ABI_CMicrosoft_CWindows_CVision_CRecognizedLineStyle __x_ABI_CMicrosoft_CWindows_CVision_CRecognizedLineStyle;

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
enum __x_ABI_CMicrosoft_CWindows_CVision_CDetectedLineStyle
    {
        __x_ABI_CMicrosoft_CWindows_CVision_CDetectedLineStyle_Handwritten = 0,
    __x_ABI_CMicrosoft_CWindows_CVision_CDetectedLineStyle_Other = 1,
};
#endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
enum __x_ABI_CMicrosoft_CWindows_CVision_COrientationDetectionOptions
    {
        __x_ABI_CMicrosoft_CWindows_CVision_COrientationDetectionOptions_None = 0,
    __x_ABI_CMicrosoft_CWindows_CVision_COrientationDetectionOptions_DetectOrientation = 1,
};
#endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
struct __x_ABI_CMicrosoft_CWindows_CVision_CBoundingBox
    {
        struct __x_ABI_CWindows_CFoundation_CPoint BottomLeft;
    struct __x_ABI_CWindows_CFoundation_CPoint BottomRight;
    struct __x_ABI_CWindows_CFoundation_CPoint TopLeft;
    struct __x_ABI_CWindows_CFoundation_CPoint TopRight;
};
#endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
struct __x_ABI_CMicrosoft_CWindows_CVision_CRecognizedLineStyle
    {
        FLOAT Confidence;
    enum __x_ABI_CMicrosoft_CWindows_CVision_CDetectedLineStyle Name;
};
#endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLineVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Text)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_BoundingBox)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This,
        struct __x_ABI_CMicrosoft_CWindows_CVision_CBoundingBox* value);
    HRESULT (STDMETHODCALLTYPE* get_Words)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This,
        UINT32* valueLength,
        __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord*** value);
    HRESULT (STDMETHODCALLTYPE* get_Style)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine* This,
        struct __x_ABI_CMicrosoft_CWindows_CVision_CRecognizedLineStyle* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLineVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLineVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedTextVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Lines)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText* This,
        UINT32* valueLength,
        __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedLine*** value);
    HRESULT (STDMETHODCALLTYPE* get_ImageAngle)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText* This,
        FLOAT* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedTextVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedTextVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWordVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Text)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_BoundingBox)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This,
        struct __x_ABI_CMicrosoft_CWindows_CVision_CBoundingBox* value);
    HRESULT (STDMETHODCALLTYPE* get_Confidence)(__x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord* This,
        FLOAT* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWordVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWordVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedWord_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* RecognizeTextFromImageAsync)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This,
        __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* imageBuffer,
        __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* options,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText** operation);
    HRESULT (STDMETHODCALLTYPE* RecognizeTextFromImage)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This,
        __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* imageBuffer,
        __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* options,
        __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText** result);
    HRESULT (STDMETHODCALLTYPE* RecognizeTextFromImageAsync2)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This,
        __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* imageBuffer,
        __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* options,
        enum __x_ABI_CMicrosoft_CWindows_CWorkloads_CWorkloadPriority priority,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CRecognizedText** operation);
    HRESULT (STDMETHODCALLTYPE* RecognizeTextFromImage2)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer* This,
        __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* imageBuffer,
        __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* options,
        enum __x_ABI_CMicrosoft_CWindows_CWorkloads_CWorkloadPriority priority,
        __x_ABI_CMicrosoft_CWindows_CVision_CIRecognizedText** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizer_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptionsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_OrientationDetection)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
        enum __x_ABI_CMicrosoft_CWindows_CVision_COrientationDetectionOptions* value);
    HRESULT (STDMETHODCALLTYPE* put_OrientationDetection)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
        enum __x_ABI_CMicrosoft_CWindows_CVision_COrientationDetectionOptions value);
    HRESULT (STDMETHODCALLTYPE* get_MaxAnalysisSize)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
        struct __x_ABI_CWindows_CGraphics_CSizeInt32* value);
    HRESULT (STDMETHODCALLTYPE* put_MaxAnalysisSize)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
        struct __x_ABI_CWindows_CGraphics_CSizeInt32 value);
    HRESULT (STDMETHODCALLTYPE* get_MaxLineCount)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
        UINT32* value);
    HRESULT (STDMETHODCALLTYPE* put_MaxLineCount)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions* This,
        UINT32 value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptionsVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptionsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerOptions_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetReadyState)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This,
        enum __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState* result);
    HRESULT (STDMETHODCALLTYPE* EnsureReadyAsync)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double** operation);
    HRESULT (STDMETHODCALLTYPE* CreateAsync)(__x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CVision__CTextRecognizer** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStaticsVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CVision_CITextRecognizerStatics_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

