// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector;

#endif // ____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory;

#endif // ____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetValues)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This,
        UINT32 valuesLength,
        FLOAT* values);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This,
        UINT32* value);
    HRESULT (STDMETHODCALLTYPE* get_VectorSpaceId)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector* This,
        GUID* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory* This,
        UINT32 dataLength,
        FLOAT* data,
        GUID vectorSpaceID,
        __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVector** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactoryVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CSemanticSearch_CIEmbeddingVectorFactory_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

