// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

typedef enum __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyResultState __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyResultState;

enum __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyResultState
    {
        __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyResultState_InProgress = 0,
    __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyResultState_Success = 1,
    __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyResultState_Failure = 2,
};

enum __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState
    {
        __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState_Ready = 0,
    __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState_EnsureNeeded = 1,
    __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState_NotSupportedOnCurrentSystem = 2,
    __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState_DisabledByUser = 3,
};

#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Error)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This,
        HRESULT* value);
    HRESULT (STDMETHODCALLTYPE* get_ErrorDisplayText)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ExtendedError)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This,
        HRESULT* value);
    HRESULT (STDMETHODCALLTYPE* get_Status)(__x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult* This,
        enum __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyResultState* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResultVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResultVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_INTERFACE_DEFINED__) */
    
