// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Windows.Graphics.Imaging.h"
#include "Windows.Storage.Streams.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics;

#endif // ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap_FWD_DEFINED__
#define ____x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap __x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap;

#endif // ____x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIBuffer_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIBuffer_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CStorage_CStreams_CIBuffer __x_ABI_CWindows_CStorage_CStreams_CIBuffer;

#endif // ____x_ABI_CWindows_CStorage_CStreams_CIBuffer_FWD_DEFINED__

typedef enum __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat;

enum __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat
    {
        __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat_Rgb8 = 137224,
    __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat_Rgba8 = 30,
    __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat_Argb8 = 2498570,
    __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat_Bgra8 = 87,
    __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat_Gray8 = 62,
};

#if !defined(____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Buffer)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
        __x_ABI_CWindows_CStorage_CStreams_CIBuffer** value);
    HRESULT (STDMETHODCALLTYPE* get_PixelFormat)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
        enum __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat* value);
    HRESULT (STDMETHODCALLTYPE* get_PixelHeight)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
        INT32* value);
    HRESULT (STDMETHODCALLTYPE* get_PixelWidth)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
        INT32* value);
    HRESULT (STDMETHODCALLTYPE* get_RowStride)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
        INT32* value);
    HRESULT (STDMETHODCALLTYPE* CopyToByteArray)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
        UINT32 valuesLength,
        BYTE* values);
    HRESULT (STDMETHODCALLTYPE* CopyToSoftwareBitmap)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer* This,
        __x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferVtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateForBuffer)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics* This,
        __x_ABI_CWindows_CStorage_CStreams_CIBuffer* buffer,
        enum __x_ABI_CMicrosoft_CGraphics_CImaging_CImageBufferPixelFormat pixelFormat,
        INT32 width,
        INT32 height,
        INT32 rowStride,
        __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer** result);
    HRESULT (STDMETHODCALLTYPE* CreateForSoftwareBitmap)(__x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics* This,
        __x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap* softwareBitmap,
        __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBuffer** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStaticsVtbl;

    interface __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CGraphics_CImaging_CIImageBufferStatics_INTERFACE_DEFINED__) */
    
